// Generated from api-wilayah-indonesia (514 kab/kota, 38 provinsi).
// Regenerate: powershell -File mobile/tool/gen_regions.ps1

const indonesianProvinces = <String>[
  'Aceh',
  'Sumatera Utara',
  'Sumatera Barat',
  'Riau',
  'Jambi',
  'Sumatera Selatan',
  'Bengkulu',
  'Lampung',
  'Kepulauan Bangka Belitung',
  'Kepulauan Riau',
  'DKI Jakarta',
  'Jawa Barat',
  'Jawa Tengah',
  'DI Yogyakarta',
  'Jawa Timur',
  'Banten',
  'Bali',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Kalimantan Barat',
  'Kalimantan Tengah',
  'Kalimantan Selatan',
  'Kalimantan Timur',
  'Kalimantan Utara',
  'Sulawesi Utara',
  'Sulawesi Tengah',
  'Sulawesi Selatan',
  'Sulawesi Tenggara',
  'Gorontalo',
  'Sulawesi Barat',
  'Maluku',
  'Maluku Utara',
  'Papua',
  'Papua Barat',
  'Papua Selatan',
  'Papua Tengah',
  'Papua Pegunungan',
  'Papua Barat Daya',
];

const indonesianCitiesByProvince = <String, List<String>>{
  'Aceh': [
    'Aceh Barat',
    'Aceh Barat Daya',
    'Aceh Besar',
    'Aceh Jaya',
    'Aceh Selatan',
    'Aceh Singkil',
    'Aceh Tamiang',
    'Aceh Tengah',
    'Aceh Tenggara',
    'Aceh Timur',
    'Aceh Utara',
    'Bener Meriah',
    'Bireuen',
    'Gayo Lues',
    'Kota Banda Aceh',
    'Kota Langsa',
    'Kota Lhokseumawe',
    'Kota Sabang',
    'Kota Subulussalam',
    'Nagan Raya',
    'Pidie',
    'Pidie Jaya',
    'Simeulue',
  ],
  'Sumatera Utara': [
    'Asahan',
    'Batu Bara',
    'Dairi',
    'Deli Serdang',
    'Humbang Hasundutan',
    'Karo',
    'Kota Binjai',
    'Kota Gunungsitoli',
    'Kota Medan',
    'Kota Padangsidimpuan',
    'Kota Pematangsiantar',
    'Kota Sibolga',
    'Kota Tanjungbalai',
    'Kota Tebing Tinggi',
    'Labuhanbatu',
    'Labuhanbatu Selatan',
    'Labuhanbatu Utara',
    'Langkat',
    'Mandailing Natal',
    'Nias',
    'Nias Barat',
    'Nias Selatan',
    'Nias Utara',
    'Padang Lawas',
    'Padang Lawas Utara',
    'Pakpak Bharat',
    'Samosir',
    'Serdang Bedagai',
    'Simalungun',
    'Tapanuli Selatan',
    'Tapanuli Tengah',
    'Tapanuli Utara',
    'Toba',
  ],
  'Sumatera Barat': [
    'Agam',
    'Dharmasraya',
    'Kepulauan Mentawai',
    'Kota Bukittinggi',
    'Kota Padang',
    'Kota Padang Panjang',
    'Kota Pariaman',
    'Kota Payakumbuh',
    'Kota Sawahlunto',
    'Kota Solok',
    'Lima Puluh Kota',
    'Padang Pariaman',
    'Pasaman',
    'Pasaman Barat',
    'Pesisir Selatan',
    'Sijunjung',
    'Solok',
    'Solok Selatan',
    'Tanah Datar',
  ],
  'Riau': [
    'Bengkalis',
    'Indragiri Hilir',
    'Indragiri Hulu',
    'Kampar',
    'Kepulauan Meranti',
    'Kota Dumai',
    'Kota Pekanbaru',
    'Kuantan Singingi',
    'Pelalawan',
    'Rokan Hilir',
    'Rokan Hulu',
    'Siak',
  ],
  'Jambi': [
    'Batanghari',
    'Bungo',
    'Kerinci',
    'Kota Jambi',
    'Kota Sungai Penuh',
    'Merangin',
    'Muaro Jambi',
    'Sarolangun',
    'Tanjung Jabung Barat',
    'Tanjung Jabung Timur',
    'Tebo',
  ],
  'Sumatera Selatan': [
    'Banyuasin',
    'Empat Lawang',
    'Kota Lubuk Linggau',
    'Kota Pagar Alam',
    'Kota Palembang',
    'Kota Prabumulih',
    'Lahat',
    'Muara Enim',
    'Musi Banyuasin',
    'Musi Rawas',
    'Musi Rawas Utara',
    'Ogan Ilir',
    'Ogan Komering Ilir',
    'Ogan Komering Ulu',
    'Ogan Komering Ulu Selatan',
    'Ogan Komering Ulu Timur',
    'Penukal Abab Lematang Ilir',
  ],
  'Bengkulu': [
    'Bengkulu Selatan',
    'Bengkulu Tengah',
    'Bengkulu Utara',
    'Kaur',
    'Kepahiang',
    'Kota Bengkulu',
    'Lebong',
    'Mukomuko',
    'Rejang Lebong',
    'Seluma',
  ],
  'Lampung': [
    'Kota Bandar Lampung',
    'Kota Metro',
    'Lampung Barat',
    'Lampung Selatan',
    'Lampung Tengah',
    'Lampung Timur',
    'Lampung Utara',
    'Mesuji',
    'Pesawaran',
    'Pesisir Barat',
    'Pringsewu',
    'Tanggamus',
    'Tulang Bawang',
    'Tulang Bawang Barat',
    'Way Kanan',
  ],
  'Kepulauan Bangka Belitung': [
    'Bangka',
    'Bangka Barat',
    'Bangka Selatan',
    'Bangka Tengah',
    'Belitung',
    'Belitung Timur',
    'Kota Pangkal Pinang',
  ],
  'Kepulauan Riau': [
    'Bintan',
    'Karimun',
    'Kepulauan Anambas',
    'Kota Batam',
    'Kota Tanjung Pinang',
    'Lingga',
    'Natuna',
  ],
  'DKI Jakarta': [
    'Administrasi Kepulauan Seribu',
    'Kota Administrasi Jakarta Barat',
    'Kota Administrasi Jakarta Pusat',
    'Kota Administrasi Jakarta Selatan',
    'Kota Administrasi Jakarta Timur',
    'Kota Administrasi Jakarta Utara',
  ],
  'Jawa Barat': [
    'Bandung',
    'Bandung Barat',
    'Bekasi',
    'Bogor',
    'Ciamis',
    'Cianjur',
    'Cirebon',
    'Garut',
    'Indramayu',
    'Karawang',
    'Kota Bandung',
    'Kota Banjar',
    'Kota Bekasi',
    'Kota Bogor',
    'Kota Cimahi',
    'Kota Cirebon',
    'Kota Depok',
    'Kota Sukabumi',
    'Kota Tasikmalaya',
    'Kuningan',
    'Majalengka',
    'Pangandaran',
    'Purwakarta',
    'Subang',
    'Sukabumi',
    'Sumedang',
    'Tasikmalaya',
  ],
  'Jawa Tengah': [
    'Banjarnegara',
    'Banyumas',
    'Batang',
    'Blora',
    'Boyolali',
    'Brebes',
    'Cilacap',
    'Demak',
    'Grobogan',
    'Jepara',
    'Karanganyar',
    'Kebumen',
    'Kendal',
    'Klaten',
    'Kota Magelang',
    'Kota Pekalongan',
    'Kota Salatiga',
    'Kota Semarang',
    'Kota Surakarta',
    'Kota Tegal',
    'Kudus',
    'Magelang',
    'Pati',
    'Pekalongan',
    'Pemalang',
    'Purbalingga',
    'Purworejo',
    'Rembang',
    'Semarang',
    'Sragen',
    'Sukoharjo',
    'Tegal',
    'Temanggung',
    'Wonogiri',
    'Wonosobo',
  ],
  'DI Yogyakarta': [
    'Bantul',
    'Gunungkidul',
    'Kota Yogyakarta',
    'Kulon Progo',
    'Sleman',
  ],
  'Jawa Timur': [
    'Bangkalan',
    'Banyuwangi',
    'Blitar',
    'Bojonegoro',
    'Bondowoso',
    'Gresik',
    'Jember',
    'Jombang',
    'Kediri',
    'Kota Batu',
    'Kota Blitar',
    'Kota Kediri',
    'Kota Madiun',
    'Kota Malang',
    'Kota Mojokerto',
    'Kota Pasuruan',
    'Kota Probolinggo',
    'Kota Surabaya',
    'Lamongan',
    'Lumajang',
    'Madiun',
    'Magetan',
    'Malang',
    'Mojokerto',
    'Nganjuk',
    'Ngawi',
    'Pacitan',
    'Pamekasan',
    'Pasuruan',
    'Ponorogo',
    'Probolinggo',
    'Sampang',
    'Sidoarjo',
    'Situbondo',
    'Sumenep',
    'Trenggalek',
    'Tuban',
    'Tulungagung',
  ],
  'Banten': [
    'Kota Cilegon',
    'Kota Serang',
    'Kota Tangerang',
    'Kota Tangerang Selatan',
    'Lebak',
    'Pandeglang',
    'Serang',
    'Tangerang',
  ],
  'Bali': [
    'Badung',
    'Bangli',
    'Buleleng',
    'Gianyar',
    'Jembrana',
    'Karangasem',
    'Klungkung',
    'Kota Denpasar',
    'Tabanan',
  ],
  'Nusa Tenggara Barat': [
    'Bima',
    'Dompu',
    'Kota Bima',
    'Kota Mataram',
    'Lombok Barat',
    'Lombok Tengah',
    'Lombok Timur',
    'Lombok Utara',
    'Sumbawa',
    'Sumbawa Barat',
  ],
  'Nusa Tenggara Timur': [
    'Alor',
    'Belu',
    'Ende',
    'Flores Timur',
    'Kota Kupang',
    'Kupang',
    'Lembata',
    'Malaka',
    'Manggarai',
    'Manggarai Barat',
    'Manggarai Timur',
    'Nagekeo',
    'Ngada',
    'Rote Ndao',
    'Sabu Raijua',
    'Sikka',
    'Sumba Barat',
    'Sumba Barat Daya',
    'Sumba Tengah',
    'Sumba Timur',
    'Timor Tengah Selatan',
    'Timor Tengah Utara',
  ],
  'Kalimantan Barat': [
    'Bengkayang',
    'Kapuas Hulu',
    'Kayong Utara',
    'Ketapang',
    'Kota Pontianak',
    'Kota Singkawang',
    'Kubu Raya',
    'Landak',
    'Melawi',
    'Mempawah',
    'Sambas',
    'Sanggau',
    'Sekadau',
    'Sintang',
  ],
  'Kalimantan Tengah': [
    'Barito Selatan',
    'Barito Timur',
    'Barito Utara',
    'Gunung Mas',
    'Kapuas',
    'Katingan',
    'Kota Palangkaraya',
    'Kotawaringin Barat',
    'Kotawaringin Timur',
    'Lamandau',
    'Murung Raya',
    'Pulang Pisau',
    'Seruyan',
    'Sukamara',
  ],
  'Kalimantan Selatan': [
    'Balangan',
    'Banjar',
    'Barito Kuala',
    'Hulu Sungai Selatan',
    'Hulu Sungai Tengah',
    'Hulu Sungai Utara',
    'Kota Banjarbaru',
    'Kota Banjarmasin',
    'Kotabaru',
    'Tabalong',
    'Tanah Bumbu',
    'Tanah Laut',
    'Tapin',
  ],
  'Kalimantan Timur': [
    'Berau',
    'Kota Balikpapan',
    'Kota Bontang',
    'Kota Samarinda',
    'Kutai Barat',
    'Kutai Kartanegara',
    'Kutai Timur',
    'Mahakam Ulu',
    'Paser',
    'Penajam Paser Utara',
  ],
  'Kalimantan Utara': [
    'Bulungan',
    'Kota Tarakan',
    'Malinau',
    'Nunukan',
    'Tana Tidung',
  ],
  'Sulawesi Utara': [
    'Bolaang Mongondow',
    'Bolaang Mongondow Selatan',
    'Bolaang Mongondow Timur',
    'Bolaang Mongondow Utara',
    'Kepulauan Sangihe',
    'Kepulauan Siau Tagulandang Biaro',
    'Kepulauan Talaud',
    'Kota Bitung',
    'Kota Kotamobagu',
    'Kota Manado',
    'Kota Tomohon',
    'Minahasa',
    'Minahasa Selatan',
    'Minahasa Tenggara',
    'Minahasa Utara',
  ],
  'Sulawesi Tengah': [
    'Banggai',
    'Banggai Kepulauan',
    'Banggai Laut',
    'Buol',
    'Donggala',
    'Kota Palu',
    'Morowali',
    'Morowali Utara',
    'Parigi Moutong',
    'Poso',
    'Sigi',
    'Tojo Una Una',
    'Toli-Toli',
  ],
  'Sulawesi Selatan': [
    'Bantaeng',
    'Barru',
    'Bone',
    'Bulukumba',
    'Enrekang',
    'Gowa',
    'Jeneponto',
    'Kepulauan Selayar',
    'Kota Makassar',
    'Kota Palopo',
    'Kota Parepare',
    'Luwu',
    'Luwu Timur',
    'Luwu Utara',
    'Maros',
    'Pangkajene dan Kepulauan',
    'Pinrang',
    'Sidenreng Rappang',
    'Sinjai',
    'Soppeng',
    'Takalar',
    'Tana Toraja',
    'Toraja Utara',
    'Wajo',
  ],
  'Sulawesi Tenggara': [
    'Bombana',
    'Buton',
    'Buton Selatan',
    'Buton Tengah',
    'Buton Utara',
    'Kolaka',
    'Kolaka Timur',
    'Kolaka Utara',
    'Konawe',
    'Konawe Kepulauan',
    'Konawe Selatan',
    'Konawe Utara',
    'Kota Bau Bau',
    'Kota Kendari',
    'Muna',
    'Muna Barat',
    'Wakatobi',
  ],
  'Gorontalo': [
    'Boalemo',
    'Bone Bolango',
    'Gorontalo',
    'Gorontalo Utara',
    'Kota Gorontalo',
    'Pohuwato',
  ],
  'Sulawesi Barat': [
    'Majene',
    'Mamasa',
    'Mamuju',
    'Mamuju Tengah',
    'Pasangkayu',
    'Polewali Mandar',
  ],
  'Maluku': [
    'Buru',
    'Buru Selatan',
    'Kepulauan Aru',
    'Kepulauan Tanimbar',
    'Kota Ambon',
    'Kota Tual',
    'Maluku Barat Daya',
    'Maluku Tengah',
    'Maluku Tenggara',
    'Seram Bagian Barat',
    'Seram Bagian Timur',
  ],
  'Maluku Utara': [
    'Halmahera Barat',
    'Halmahera Selatan',
    'Halmahera Tengah',
    'Halmahera Timur',
    'Halmahera Utara',
    'Kepulauan Sula',
    'Kota Ternate',
    'Kota Tidore Kepulauan',
    'Pulau Morotai',
    'Pulau Taliabu',
  ],
  'Papua': [
    'Biak Numfor',
    'Jayapura',
    'Keerom',
    'Kepulauan Yapen',
    'Kota Jayapura',
    'Mamberamo Raya',
    'Sarmi',
    'Supiori',
    'Waropen',
  ],
  'Papua Barat': [
    'Fak Fak',
    'Kaimana',
    'Manokwari',
    'Manokwari Selatan',
    'Pegunungan Arfak',
    'Teluk Bintuni',
    'Teluk Wondama',
  ],
  'Papua Selatan': [
    'Asmat',
    'Boven Digoel',
    'Mappi',
    'Merauke',
  ],
  'Papua Tengah': [
    'Deiyai',
    'Dogiyai',
    'Intan Jaya',
    'Mimika',
    'Nabire',
    'Paniai',
    'Puncak',
    'Puncak Jaya',
  ],
  'Papua Pegunungan': [
    'Jayawijaya',
    'Lanny Jaya',
    'Mamberamo Tengah',
    'Nduga',
    'Pegunungan Bintang',
    'Tolikara',
    'Yahukimo',
    'Yalimo',
  ],
  'Papua Barat Daya': [
    'Kota Sorong',
    'Maybrat',
    'Raja Ampat',
    'Sorong',
    'Sorong Selatan',
    'Tambrauw',
  ],
};

List<String> citiesForProvince(String province) {
  if (province == 'Semua' || province.isEmpty) return const [];
  return List<String>.from(indonesianCitiesByProvince[province] ?? const <String>[]);
}

String normalizeRegionName(String raw) {
  var s = raw.trim();
  s = s.replaceFirst(RegExp(r'^(kabupaten|kab\.?|kota)\s+', caseSensitive: false), '').trim();
  return s.toLowerCase();
}

bool regionNameMatch(String a, String b) {
  if (a.isEmpty || b.isEmpty) return false;
  return normalizeRegionName(a) == normalizeRegionName(b);
}
